# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: order.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'order.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0border.proto\"F\n\x12\x43reateOrderRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\x03\x12\x1f\n\x0border_items\x18\x02 \x03(\x0b\x32\n.OrderItem\"G\n\tOrderItem\x12\x14\n\x0cproduct_code\x18\x01 \x01(\t\x12\x12\n\nunit_price\x18\x02 \x01(\x02\x12\x10\n\x08quantity\x18\x03 \x01(\x05\"\'\n\x13\x43reateOrderResponse\x12\x10\n\x08order_id\x18\x01 \x01(\x03\"#\n\x0fGetOrderRequest\x12\x10\n\x08order_id\x18\x01 \x01(\x03\"D\n\x10GetOrderResponse\x12\x0f\n\x07user_id\x18\x01 \x01(\x03\x12\x1f\n\x0border_items\x18\x02 \x03(\x0b\x32\n.OrderItem2l\n\x05Order\x12\x35\n\x06\x43reate\x12\x13.CreateOrderRequest\x1a\x14.CreateOrderResponse\"\x00\x12,\n\x03Get\x12\x10.GetOrderRequest\x1a\x11.GetOrderResponse\"\x00\x42-Z+github.com/k0ntra/microservices-proto/orderb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'order_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z+github.com/k0ntra/microservices-proto/order'
  _globals['_CREATEORDERREQUEST']._serialized_start=15
  _globals['_CREATEORDERREQUEST']._serialized_end=85
  _globals['_ORDERITEM']._serialized_start=87
  _globals['_ORDERITEM']._serialized_end=158
  _globals['_CREATEORDERRESPONSE']._serialized_start=160
  _globals['_CREATEORDERRESPONSE']._serialized_end=199
  _globals['_GETORDERREQUEST']._serialized_start=201
  _globals['_GETORDERREQUEST']._serialized_end=236
  _globals['_GETORDERRESPONSE']._serialized_start=238
  _globals['_GETORDERRESPONSE']._serialized_end=306
  _globals['_ORDER']._serialized_start=308
  _globals['_ORDER']._serialized_end=416
# @@protoc_insertion_point(module_scope)
